Clinica_Website/urls.py
from django.urls import path,include
from django.contrib import admin

urlpatterns = [
    path('', include('Registros.urls'),name='inicio'),
    path('admin/', admin.site.urls),
]

Registros/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import login,logout_then_login
from django.contrib.auth.decorators import login_required
app_name='registros'

urlpatterns = [
	
	path('', views.IndexView.as_view(),name='index'),

	path('pdf/',login_required(views.PDFPrueba.as_view()),name='pdf'),
	path('pdf/ecomamas/<ident>',login_required(views.info_ecomamas.as_view()),name='info_ecomamas'),


	path('buscar/',login_required(views.BusquedaView.as_view()),name='buscar'),
	path('buscar_ajax/',login_required(views.BusquedaAjaxView.as_view()),name='buscarajax'),

	path('accounts/login/',login,{'template_name':'registros/login.html'},name='login'),
	path('logout/',logout_then_login,name='logout'),

	path('nuevopaciente/', login_required(views.Crear_paciente.as_view()),name='newpaciente'),

	path('paciente/<ident>', login_required(views.IngresoView.as_view()),name='paciente'),
	path('ecografia/<ident>', login_required(views.EcoView.as_view()),name='ecografia'),

	path('ecomama/<ident>', login_required(views.EcomamaCreate.as_view()),name='ecomama'),
	path('ecoabdomen/<ident>', login_required(views.EcoabdomenCreate.as_view()),name='ecoabdomen'),
	path('ecoobstetrico/<ident>', login_required(views.EcoobstetricoCreate.as_view()),name='ecoobstetrico'),
	path('ecorenal/<ident>', login_required(views.EcorenalCreate.as_view()),name='ecorenal'),
	path('ecoginecologia/<ident>', login_required(views.EcoginecologiaCreate.as_view()),name='ecoginecologia'),
	path('ecotesticular/<ident>', login_required(views.EcotesticularCreate.as_view()),name='ecotesticular'),
	path('ekg/<ident>', login_required(views.EkgCreate.as_view()),name='ekg'),
	path('terapias/<ident>', login_required(views.TerapiaCreate.as_view()),name='terapias'),
	path('rayosx/<ident>',login_required(views.RayosxCreate.as_view()),name='rayosx'),
	path('desintometria/<ident>', login_required(views.DesintometriaCreate.as_view()),name='desintometria'),
	path('analisis/<ident>', login_required(views.AnalisisCreate.as_view()),name='analisis'),

	path('ecomama/listar/<pk>', login_required(views.Listecomamas.as_view()),name='listar_ecomama'),
	path('ecoabdomen/listar/<pk>', login_required(views.Listecoabdomen.as_view()),name='listar_ecoabdomen'),
	path('ecoobstetrico/listar/<pk>', login_required(views.Listecoobstetrico.as_view()),name='listar_ecoobstetrico'),
	path('ecorenal/listar/<pk>', login_required(views.Listecorenal.as_view()),name='listar_ecorenal'),
	path('ecoginecologia/listar/<pk>', login_required(views.Listecoginecologo.as_view()),name='listar_ecoginecologia'),
	path('ecotesticular/listar/<pk>',login_required(views.Listecotesticular.as_view()),name='listar_ecotesticular'),
	path('analisis/listar/<pk>',login_required(views.ListeAnalisisclinico.as_view()),name='listar_analisis'),
	path('rayosx/listar/<pk>',login_required(views.ListeRayosx.as_view()),name='listar_rayosx'),
	path('desintometria/listar/<pk>',login_required(views.ListeDesintrometria.as_view()),name='listar_desintometria'),
	path('ekg/listar/<pk>',login_required(views.ListeEkg.as_view()),name='listar_ekg'),
	path('terapias/listar/<pk>',login_required(views.ListeTerapias.as_view()),name='listar_terapias'),

	path('paciente/listar_diagnostico/<pk>', login_required(views.ListDiagnostico.as_view()),name='lista_diagnostico'),
	path('paciente/nuevodiagnostico/<ident>', login_required(views.CreateOrderView.as_view()),name='nuevo_diagnostico'),

]

Registros/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime,timedelta
from django.utils.timezone import now
from django.urls import reverse
# Create your models here.

class Paciente(models.Model):
	cedula=models.CharField(max_length=13,unique=True,verbose_name='Cedula de indentidad')
	nombre1=models.CharField(max_length=50,verbose_name='Primer nombre')
	nombre2=models.CharField(max_length=50,verbose_name='Segundo nombre')
	apellPadre=models.CharField(max_length=50,verbose_name='Apellido paterno')
	apellMadre=models.CharField(max_length=50,verbose_name='Apellido materno')
	sexo=models.CharField(max_length=2,choices=(('F', 'Femenino'),('M', 'Masculino'),))
	direccion=models.CharField(max_length=100,verbose_name='DIRECCION DOMICILIARIA')
	fechNacimiento=models.DateField('fecha de naciemiento',default=timezone.now)
	lugarNacimiento=models.CharField(max_length=100,verbose_name='LUGAR DE NACIMIENTO')
	nacionalidad=models.CharField(max_length=100,verbose_name='NACIONALIDAD')
	grupoCultural=models.CharField(max_length=100,verbose_name='GRUPO CULTURAL')
	estadoCivil=models.CharField(max_length=3,choices=(('SOL', 'Soltero'),('CAS', 'Casado'),('DIV', 'Divorciado'),('VIU', 'Viudo'),('UNL', 'Unión libre')))
	instruccion=models.CharField(max_length=100,verbose_name='INSTRUCION EDUCATIVA')
	ocupacion=models.CharField(max_length=100,verbose_name='OCUPACION')
	empresa=models.CharField(max_length=100,verbose_name='EMPRESA')
	tipo_sangre=models.CharField(max_length=100,verbose_name='TIPO DE SANGRE')
	tipo_seguro=models.CharField(max_length=100,verbose_name='TIPO DE SEGURIDAD')
	telefono=models.CharField(max_length=9,verbose_name='Telefono del paciente')
	celular=models.CharField(max_length=10,verbose_name='Celular del paciente')
	correo=models.EmailField(verbose_name='Correo del paciente')
	pariente=models.CharField(max_length=100,verbose_name='NOMBRE PARIENTE')
	parentesco=models.CharField(max_length=100,verbose_name='Parentesco')
	telefono_pariente=models.CharField(max_length=9,verbose_name='Telefono del pariente')
	celular_pariente=models.CharField(max_length=10,verbose_name='Celular del referido')
	foto=models.ImageField(upload_to='fotos', null=True,blank=True)
	fech_creado=models.DateTimeField(auto_now_add=True,verbose_name='Fecha de admision')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='FECHA DE ACTUALIZACION')

	def get_absolute_url(self):
		return reverse('registros:detail',kwargs={'pk':self.pk})

	def __str__(self):
		return self.apellPadre+' '+self.apellMadre+' '+self.nombre1+' '+self.nombre2

class Diagnostico(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	precion_arterial=models.CharField(max_length=30,verbose_name='PRESION ARTERIAL')
	temperatura=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='TEMPERATURA(°C)')
	peso=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='PESO(KG)')
	evolucion=models.CharField(max_length=300,verbose_name='EVOLUCION')
	pulso=models.CharField(max_length=20,verbose_name='PULSO')
	saturacion_oxigeno=models.CharField(max_length=20,verbose_name='SATURACION DE OXIGENO')
	talla=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='ESTATURA')
	idx=models.CharField(max_length=100,verbose_name='IDX')
	exmenes=models.CharField(max_length=200,verbose_name='EXAMENES')
	motivo=models.CharField(max_length=300,verbose_name='MOTIVO')
	fechaDiagnostico=models.DateTimeField(auto_now_add=True,verbose_name='FECHA DE DIAGNOSTICO')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='FECHA DE ACTUALIZACION')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)

class farmacoterapia(models.Model):
	diagnostico= models.ForeignKey(Diagnostico, on_delete=models.CASCADE,verbose_name='Diagnostico')
	farmaco=models.CharField(max_length=300,verbose_name='Farmaco')
	adminitracion=models.CharField(max_length=300,verbose_name='Administracion')
	comentario=models.CharField(max_length=300,verbose_name='Comentario')

class analisisMamas(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	tegGlandularizq=models.CharField(max_length=20,choices=(('HOMOGENEO', 'Homogéneo'),('HETEROGENEO', 'Heterogéneo')))
	infotegGlandularizq=models.CharField(max_length=100)
	tegGlandularder=models.CharField(max_length=20,choices=(('HOMOGENEO', 'Homogéneo'),('HETEROGENEO', 'Heterogéneo')))
	infotegGlandularder=models.CharField(max_length=100)
	bordesizq=models.CharField(max_length=20,choices=(('REGULAR', 'Regulares'),('IRREGULAR', 'Irregulares')))
	bordesder=models.CharField(max_length=20,choices=(('REGULAR', 'Regulares'),('IRREGULAR', 'Irregulares')))
	ecogenidadizq=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('DISMINUIDA', 'Disminuida'),('AUMENTADA', 'Aumentada')))
	ecogenidadder=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('DISMINUIDA', 'Disminuida'),('AUMENTADA', 'Aumentada')))
	tejGrasoizq=models.CharField(max_length=20,choices=(('BUENA', 'Buena Cantidad'),('POCA', 'Poca Cantidad')))
	tejGrasoder=models.CharField(max_length=20,choices=(('BUENA', 'Buena Cantidad'),('POCA', 'Poca Cantidad')))
	imgExpansivasizq=models.CharField(max_length=20,choices=(('NO', 'No'),('QUISTICA', 'Quísticas'),('SOLIDA', 'Sólidas')))
	imgExpansivasder=models.CharField(max_length=20,choices=(('NO', 'No'),('QUISTICA', 'Quísticas'),('SOLIDA', 'Sólidas')))
	horarioizq=models.CharField(max_length=400,verbose_name='HORARIO')
	horarioder=models.CharField(max_length=400,verbose_name='HORARIO')
	descripcionizq=models.CharField(max_length=500,verbose_name='DESCRIPCION')
	descripcionder=models.CharField(max_length=500,verbose_name='DESCRIPCION')
	observaciones=models.CharField(max_length=500,verbose_name='OBSERBACIONES')
	presuncion=models.CharField(max_length=800,verbose_name='PRESIÓN DIAGNÓSTICA')
	fech_analisismamas=models.DateTimeField(auto_now_add=True,verbose_name='FECHA DE ADMISION')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='FECHA DE ACTUALIZACION')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)
	def get_absolute_url(self):
		return reverse('registros:ecografia')

class analisisAbdominal(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	movilidad_higado=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('ANORMAL', 'Anormal')))
	bordes_higado=models.CharField(max_length=20,choices=(('REGULAR', 'Regulares'),('IRREGULAR', 'Irregulares')))
	dimension_higado=models.CharField(max_length=20,choices=(('NORMALES', 'Normales'),('OTROS', 'Otros')))
	parenquima_higado=models.CharField(max_length=20,choices=(('HOMOGENEO', 'Homogéneo'),('HETEROGENEO', 'Heterogéneo')))
	ecogenicidad_higado=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('DISMINUIDA', 'Disminuida'),('AUMENTADA', 'Aumentada')))
	imgExpansivas_higado=models.CharField(max_length=2,choices=(('NO', 'No'),('SI', 'Si')))
	dilatacionVilar_higado=models.CharField(max_length=2,choices=(('NO', 'No'),('SI', 'Si')))
	coledoco_higado=models.CharField(max_length=200,verbose_name='COLEDOCO')
	forma_vesicula=models.CharField(max_length=200,verbose_name='FORMA')
	paredes_vesicula=models.CharField(max_length=20,choices=(('REGULAR', 'Regulares'),('IRREGULAR', 'Irregulares')))
	contenidoanecoico_vesicula=models.CharField(max_length=2,choices=(('NO', 'No'),('SI', 'Si')))
	calculointerno_vesicula=models.CharField(max_length=200,verbose_name='CALCULOS INTERNOS')
	diametrotransverso_vesicula=models.CharField(max_length=200,verbose_name='DIAMETRO TRANSVERSOS')
	ecogenicidad_pancreas=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('ANORMAL', 'Anormal')))
	medidas_pancreas=models.CharField(max_length=200,verbose_name='MEDIDAS')
	ecogenidad_bazo=models.CharField(max_length=20,choices=(('NORMAL', 'Normal'),('ANORMAL', 'Anormal')))
	medidas_bazo=models.CharField(max_length=200,verbose_name='MEDIDAS')
	aorta=models.CharField(max_length=200,verbose_name='CALIBRES')
	liquido_abdominal=models.CharField(max_length=2,choices=(('NO', 'No'),('SI', 'Si')))
	observaciones=models.CharField(max_length=200,verbose_name='OBSERBACIONES')
	presuncion_diagnostico=models.CharField(max_length=500,verbose_name='PRESUNCION_DIAGNOSTICA')
	fech_analisisabdomen=models.DateTimeField(auto_now_add=True,verbose_name='FECHA DE ADMISION')
	fech_actualizado=models.DateTimeField(auto_now=True,verbose_name='FECHA DE ACTUALIZACION')
	encargado = models.CharField(max_length=30,verbose_name='ENCARGADO',blank=True,null=True)

	def get_absolute_url(self):
		return reverse('registros:ecografia')

	def __str__(self):
		return str(self.paciente)+' '+str(self.fech_analisisabdomen)

class analisisObstetrico(models.Model):
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,verbose_name='PACIENTE')
	numero=models.PositiveSmallIntegerField(default=1)
	situacion=models.CharField(max_length=20,choices=(('LONGITUDINAL', 'Longitudinal'),('TRANSVERSAL', 'TRANSVERSAL'),('OBLICUA', 'Oblicua')))
	presentacion=models.CharField(max_length=20,choices=(('CEFALICO', 'Cefalico'),('PODALICO', 'Podalico'),('OTROS', 'Otros')))
	dorso=models.CharField(max_length=20,choices=(('IZQUIERDA', 'Izquierda'),('DERECHA', 'Derecha'),('ANTERIOR', 'Anterior'),('POSTERIOR', 'Posterior')))
	dbp=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='DBP(mm)')
	lf=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='LF(mm)')
	sg=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='SG(mm)')
	lcn=models.DecimalField(max_digits=10, decimal_places=2,verbose_name='LCN(mm)')
	columnaVertebral=models.CharField(max_length=20,choices=(('PRESENTE', 'Presente'),('CAMARA GASTRICA', 'Camara Gástrica')))
	riñon=models.CharField(max_length=20,choices=(('PRESENTE', 'Presente'),('VEJIGA', 'Vejiga')))

Registros/forms.py
from django import forms
from .models import analisisMamas
from django.utils.timezone import now
from django.utils import timezone

Registros/templates/registros/base_form.html
{% extends 'registros/base.html' %}

{% load crispy_forms_tags %}

{% block title %}{% endblock %}

{% block principal %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'registros:index'%}">Inicio</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'registros:buscar'%}">Busqueda de pacientes</a>
</li>
{% endblock %}

{%block derecha%}
</div>
<div style="color:aliceblue">PACIENTE : {{paciente.nombre1}}&nbsp{{paciente.nombre2}}&nbsp{{paciente.apellPadre}}&nbsp{{paciente.apellMadre}}
</div>
{%endblock%}

{% block lista %}
<li class="breadcrumb-item"><a href="{% url 'registros:index'%}">Inicio</a></li>
<li class="breadcrumb-item"><a href="{% url 'registros:buscar'%}">Busqueda</a></li>
<li class="breadcrumb-item"><a href="{% url 'registros:paciente' ident=paciente.pk %}">Paciente</a></li>
<li class="breadcrumb-item"><a href="{% url 'registros:ecografia' ident=paciente.pk %}">Ecografias</a></li>
{% block tipoeco %}{% endblock %}

{% endblock %}

{% block content %}

<div class="row">
  <div class="col-md-4">
    </div>
<div class="col-md-4">
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="GUARADAR">
    </form>
</div>
</div>
{% endblock %}

Registros/templates/registros/ecografias.html
{% extends 'registros/base.html'%}
{% block title %}Ecografias{% endblock %}

{% block principal %}
<li class="nav-item">
	<a class="nav-link" href="{% url 'registros:index'%}">Inicio</a>
</li>
<li class="nav-item active">
	<a class="nav-link" href="{% url 'registros:buscar'%}">Busqueda de pacientes</a>
</li>
{% endblock %}

{%block derecha%}
</div>
<div style="color:aliceblue">PACIENTE :
	{{datos.nombre1}}&nbsp{{datos.nombre2}}&nbsp{{datos.apellPadre}}&nbsp{{datos.apellMadre}}
</div>
{%endblock%}

{% block lista %}
<li class="breadcrumb-item"><a href="{% url 'registros:index'%}">Inicio</a></li>
<li class="breadcrumb-item"><a href="{% url 'registros:buscar'%}">Busqueda</a></li>
<li class="breadcrumb-item"><a href="{% url 'registros:paciente' ident=datos.pk %}">Paciente</a></li>
<li class="breadcrumb-item active" aria-current="page">Ecografias</li>
{% endblock %}


{% block content %}

<br>
<br>


<div class="card-deck">
		<div class="card text-white bg-primary border border-dark ml-4 mr-2 ">
				<!-- <img class="card-img-top" src="" alt="Card image cap"> -->
				<div class="card-body">
					<h5 class="card-title text-dark text-center">ECOGRAFIA ABDOMINAL</h5>
				</div>
				<div class="card-footer text-muted bg-light btn btn-justify">
					<a href="{% url 'registros:ecoabdomen' ident=datos.pk%}" class="btn btn-outline-success">NUEVO</a>
					<a href="{% url 'registros:listar_ecoabdomen'  pk=datos.pk%}" class="btn btn-outline-info">LISTAR</a>
				</div>
			</div>
		
		
		
			<div class="card text-white bg-primary border border-dark mx-2">
				<!-- <img class="card-img-top" src="" alt="Card image cap"> -->
				<div class="card-body">
					<h5 class="card-title text-dark text-center">ECOGRAFIA RENAL</h5>
				</div>
				<div class="card-footer text-muted bg-light btn btn-justify">
					<a href="{% url 'registros:ecorenal' ident=datos.pk%}" class="btn btn-outline-success">NUEVO</a>
					<a href="{% url 'registros:listar_ecorenal'  pk=datos.pk%}" class="btn btn-outline-info">LISTAR</a>
				</div>
			</div>
	{%if datos.sexo in 'F' %}
	<div class="card text-white bg-primary border border-dark mx-2">
		<!-- <img class="card-img-top" src="" alt="Card image cap"> -->
		<div class="card-body">
			<h5 class="card-title text-dark text-center">ECOGRAFIA DE MAMAS</h5>
		</div>
		<div class="card-footer text-muted bg-light btn btn-justify">
			<a href="{% url 'registros:ecomama'  ident=datos.pk%}" class="btn btn-outline-success">NUEVO</a>
			<a href="{% url 'registros:listar_ecomama'  pk=datos.pk%}" class="btn btn-outline-info">LISTAR</a>
		</div>
	</div>

	<div class="card text-white bg-primary border border-dark mx-2">
			<!-- <img class="card-img-top" src="" alt="Card image cap"> -->
			<div class="card-body">
				<h5 class="card-title text-dark text-center">ECOGRAFIA OBSTETRICO</h5>
			</div>
			<div class="card-footer text-muted bg-light btn btn-justify">
				<a href="{% url 'registros:ecoobstetrico' ident=datos.pk%}" class="btn btn-outline-success">NUEVO</a>
				<a href="{% url 'registros:listar_ecoobstetrico'  pk=datos.pk%}" class="btn btn-outline-info">LISTAR</a>
			</div>
		</div>
		<div class="card text-white bg-primary border border-dark ml-2 mr-4">
				<!-- <img class="card-img-top" src="" alt="Card image cap"> -->
				<div class="card-body">
					<h5 class="card-title text-center text-dark">ECOGRAFIA GINECOLOGICO</h5>
				</div>
				<div class="card-footer text-muted bg-light btn btn-justify">
					<a href="{% url 'registros:ecoginecologia' ident=datos.pk%}" class="btn btn-outline-success">NUEVO</a>
					<a href="{% url 'registros:listar_ecoginecologia'  pk=datos.pk%}" class="btn btn-outline-info">LISTAR</a>
				</div>
			</div>
	{%endif%}


	{%if datos.sexo in 'M' %}
	<div class="card text-white bg-primary border border-dark ml-2 mr-4">
			<!-- <img class="card-img-top" src="" alt="Card image cap"> -->
			<div class="card-body">
				<h5 class="card-title text-center text-dark">ECOGRAFIA TESTICULAR</h5>
			</div>
			<div class="card-footer text-muted bg-light btn btn-justify">
				<a href="{% url 'registros:ecotesticular' ident=datos.pk%}" class="btn btn-outline-success">NUEVO</a>
				<a href="{% url 'registros:listar_ecotesticular'  pk=datos.pk%}" class="btn btn-outline-info">LISTAR</a>
			</div>
		</div>
	{%endif%}

</div>
{% endblock %}

Registros/templates/registros/paciente.html
{% extends 'registros/base.html'%}
{% block title %}Opciones del paciente{% endblock %}

{% block principal %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'registros:index'%}">Inicio</a>
</li>
<li class="nav-item active">
  <a class="nav-link" href="{% url 'registros:buscar'%}">Busqueda de pacientes</a>
</li>
{% endblock %}

{%block derecha%}
</div>
<div style="color:aliceblue">PACIENTE : {{datos.nombre1}}&nbsp{{datos.nombre2}}&nbsp{{datos.apellPadre}}&nbsp{{datos.apellMadre}}
</div>
{%endblock%}

{% block lista %}
<li class="breadcrumb-item"><a href="{% url 'registros:index'%}">Inicio</a></li>
<li class="breadcrumb-item"><a href="{% url 'registros:buscar'%}">Busqueda</a></li>
<li class="breadcrumb-item active" aria-current="page">Paciente</li>
{% endblock %}



{% block content %}

<br>
<br>

<div class="card-deck">

	<div class="card  text-white  bg-primary border border-dark ml-4 mr-2s">
		<!-- <img class="card-img-top" src="diagnostico.png" alt="Card image cap"> -->
		<div class="card-body">
			<h5 class="card-title text-dark">DIAGNOTICO</h5>
			<p class="card-text">Historial clinico del paciente</p>
		</div>
		<div class="card-footer text-muted bg-light">
				
			<a href="{% url 'registros:nuevo_diagnostico' datos.pk%}" class="btn btn-outline-success">NUEVO</a>
			<a href="{% url 'registros:lista_diagnostico' datos.pk%}" class="btn btn-outline-info">LISTAR</a>
		</div>
	</div>

	<div class="card text-white bg-info border border-dark mx-2">
		<!-- <img class="card-img-top" src="ecografias.jpg" alt="Card image cap"> -->
		<div class="card-body">
			<h5 class="card-title text-dark">ECOGRAFIAS</h5>
			<p class="card-text">Informacion de las distintas ecografias</p>
		</div>
		<div class="card-footer text-muted bg-light">

			<a href="{% url 'registros:ecografia' ident=datos.pk%}" class="btn btn-outline-success">ELEGIR ECOGRAFIA</a>
		</div>
	</div>

	<div class="card text-white bg-primary border border-dark mx-2">
		<!-- <img class="card-img-top" src="rayos x.jpg" alt="Card image cap"> -->
		<div class="card-body">
			<h5 class="card-title text-dark">RAYOS X</h5>
			<p class="card-text">Historial clinico del paciente</p>
		</div>
		<div class="card-footer text-muted bg-light">
			<a href="{% url 'registros:rayosx' ident=datos.pk%}" class="btn btn-outline-success">NUEVO</a>
			<a href="{% url 'registros:listar_rayosx' datos.pk%}" class="btn btn-outline-info">LISTAR</a>
		</div>
	</div>

	<div class="card text-white bg-info border border-dark mx-2">
		<!-- <img class="card-img-top" src="desintrometria.jpg" alt="Card image cap"> -->
		<div class="card-body">
			<h5 class="card-title text-dark">DESINTROMETRIA</h5>
			<p class="card-text">Historial clinico del paciente</p>
		</div>
		<div class="card-footer text-muted bg-light">
			<a href="{% url 'registros:desintometria' ident=datos.pk%}" class="btn btn-outline-success">NUEVO</a>
			<a href="{% url 'registros:listar_desintometria' datos.pk%}" class="btn btn-outline-info">LISTAR</a>
		</div>
	</div>

	<div class="card text-white bg-primary border border-dark mx-2">
		<!-- <img class="card-img-top" src="terapias.jpg" alt="Card image cap"> -->
		<div class="card-body">
			<h5 class="card-title text-dark">TERAPIAS</h5>
			<p class="card-text">Historial clinico del paciente</p>
		</div>
		<div class="card-footer text-muted bg-light">
			<a href="{% url 'registros:terapias' ident=datos.pk%}" class="btn btn-outline-success">NUEVO</a>
			<a href="{% url 'registros:listar_terapias' datos.pk%}" class="btn btn-outline-info">LISTAR</a>
		</div>
	</div>
	<div class="card text-white bg-info border border-dark ml-2 mr-4">
		<!-- <img class="card-img-top" src="EKG.jpg" alt="Card image cap"> -->
		<div class="card-body">
			<h5 class="card-title text-dark">EKG</h5>
			<p class="card-text">Historial clinico del paciente</p>
		</div>
		<div class="card-footer text-muted bg-light">
			<a href="{% url 'registros:ekg' ident=datos.pk%}" class="btn btn-outline-success">NUEVO</a>
			<a href="{% url 'registros:listar_ekg' datos.pk%}" class="btn btn-outline-info">LISTAR</a>
		</div>
	</div>
	<div class="card text-white bg-info border border-dark ml-2 mr-4">
		<!-- <img class="card-img-top" src="EKG.jpg" alt="Card image cap"> -->
		<div class="card-body">
			<h5 class="card-title text-dark">Analisis Clinico</h5>
			<p class="card-text">Analisi clinico del paciente</p>
		</div>
		<div class="card-footer text-muted bg-light">
			<a href="{% url 'registros:analisis' ident=datos.pk%}" class="btn btn-outline-success">NUEVO</a>
			<a href="{% url 'registros:listar_analisis' datos.pk%}" class="btn btn-outline-info">LISTAR</a>
		</div>
	</div>

</div>
<div class="card-deck"></div>
{% endblock %}