Clinica_Website/urls.py
from django.urls import path,include
from django.contrib import admin

urlpatterns = [
    path('', include('Registros.urls'),name='inicio'),
    path('admin/', admin.site.urls),
]

Registros/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import login,logout_then_login
from django.contrib.auth.decorators import login_required
app_name='registros'

urlpatterns = [
	
	path('', views.IndexView.as_view(),name='index'),

	path('pdf/',login_required(views.PDFPrueba.as_view()),name='pdf'),
	path('pdf/ecomamas/<ident>',login_required(views.info_ecomamas.as_view()),name='info_ecomamas'),


	path('buscar/',login_required(views.BusquedaView.as_view()),name='buscar'),
	path('buscar_ajax/',login_required(views.BusquedaAjaxView.as_view()),name='buscarajax'),

	path('accounts/login/',login,{'template_name':'registros/login.html'},name='login'),
	path('logout/',logout_then_login,name='logout'),

	path('nuevopaciente/', login_required(views.Crear_paciente.as_view()),name='newpaciente'),

	path('paciente/<ident>', login_required(views.IngresoView.as_view()),name='paciente'),
	path('ecografia/<ident>', login_required(views.EcoView.as_view()),name='ecografia'),

	path('ecomama/<ident>', login_required(views.EcomamaCreate.as_view()),name='ecomama'),
	path('ecoabdomen/<ident>', login_required(views.EcoabdomenCreate.as_view()),name='ecoabdomen'),
	path('ecoobstetrico/<ident>', login_required(views.EcoobstetricoCreate.as_view()),name='ecoobstetrico'),
	path('ecorenal/<ident>', login_required(views.EcorenalCreate.as_view()),name='ecorenal'),
	path('ecoginecologia/<ident>', login_required(views.EcoginecologiaCreate.as_view()),name='ecoginecologia'),
	path('ecotesticular/<ident>', login_required(views.EcotesticularCreate.as_view()),name='ecotesticular'),
	path('ekg/<ident>', login_required(views.EkgCreate.as_view()),name='ekg'),
	path('terapias/<ident>', login_required(views.TerapiaCreate.as_view()),name='terapias'),
	path('rayosx/<ident>',login_required(views.RayosxCreate.as_view()),name='rayosx'),
	path('desintometria/<ident>', login_required(views.DesintometriaCreate.as_view()),name='desintometria'),
	path('analisis/<ident>', login_required(views.AnalisisCreate.as_view()),name='analisis'),

	path('ecomama/listar/<pk>', login_required(views.Listecomamas.as_view()),name='listar_ecomama'),
	path('ecoabdomen/listar/<pk>', login_required(views.Listecoabdomen.as_view()),name='listar_ecoabdomen'),
	path('ecoobstetrico/listar/<pk>', login_required(views.Listecoobstetrico.as_view()),name='listar_ecoobstetrico'),
	path('ecorenal/listar/<pk>', login_required(views.Listecorenal.as_view()),name='listar_ecorenal'),
	path('ecoginecologia/listar/<pk>', login_required(views.Listecoginecologo.as_view()),name='listar_ecoginecologia'),
	path('ecotesticular/listar/<pk>',login_required(views.Listecotesticular.as_view()),name='listar_ecotesticular'),
	path('analisis/listar/<pk>',login_required(views.ListeAnalisisclinico.as_view()),name='listar_analisis'),
	path('rayosx/listar/<pk>',login_required(views.ListeRayosx.as_view()),name='listar_rayosx'),
	path('desintometria/listar/<pk>',login_required(views.ListeDesintrometria.as_view()),name='listar_desintometria'),
	path('ekg/listar/<pk>',login_required(views.ListeEkg.as_view()),name='listar_ekg'),
	path('terapias/listar/<pk>',login_required(views.ListeTerapias.as_view()),name='listar_terapias'),

	path('paciente/listar_diagnostico/<pk>', login_required(views.ListDiagnostico.as_view()),name='lista_diagnostico'),
	path('paciente/nuevodiagnostico/<ident>', login_required(views.CreateOrderView.as_view()),name='nuevo_diagnostico'),

]

Registros/forms.py
from django import forms
from .models import analisisMamas
from django.utils.timezone import now
from django.utils import timezone

Registros/views.py
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
import datetime
from django.views.generic import ListView,DetailView,View
from django.views import View
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.urls import reverse
from .models import Paciente,Diagnostico,analisisMamas,analisisAbdominal,analisisObstetrico,ecografiaRenal,ecografiaginecologico,ecografiatesticular,farmacoterapia,ekg,terapias,rayosx,desintometria,lab_analisisclinico
from django.shortcuts import render
from django.views.generic import TemplateView
from django.core import serializers
from django.http import HttpResponse
from extra_views import CreateWithInlinesView,InlineFormSetFactory
from dateutil import relativedelta as rdelta
from datetime import date,datetime


from Clinica_Website.utileria import render_pdf

#############################################
############ crear pdf              #########
#############################################

def edad_paciente(d1):
    d2 = datetime.now()
    rd = rdelta.relativedelta(d2,d1)
    return "{0.years} years and {0.months} months".format(rd)

class PDFPrueba(View):
    """
    REGRESA PDF basando en template
    """
    def get(self,request,*args,**kwargs):
        datos = {
            "nombre" : "Michael",
            "apellidos" : "Merchan"
        }
        pdf = render_pdf("registros/mi_pdf.html",{"datos":datos})
        
        return HttpResponse(pdf,content_type="application/pdf")

class info_ecomamas(View):
    """
    REGRESA PDF basando en template
    """
    def get(self,request,*args,**kwargs):
        parametro = self.kwargs.get('ident',None)
        
        datos = ecografiaRenal.objects.get(id=parametro)
        extra={'titulo':'pdf_info_renal','clinica':'NOMBRE DE LA CLINICA','informe':'Informe Ecografia Renal','edad':edad_paciente(datos.paciente.fechNacimiento)}
        pdf = render_pdf("registros/pdf/info_cliente_pdf.html",{"datos":datos,"extra":extra})
        
        return HttpResponse(pdf,content_type="application/pdf")

#############################################
############ crear nuevo diagnostico#########
#############################################


def get_initial_pri(self, **kwargs):
    parametro = self.kwargs.get('ident',None)
    paciente = Paciente.objects.get(pk=parametro)
    return {'paciente':paciente,}

def get_context_data_pri(self, nomclass,extra,**kwargs):
    parametro = self.kwargs.get('ident',None)
    paciente = Paciente.objects.get(pk=parametro)
    context = super(nomclass, self).get_context_data(**kwargs) 
    context['paciente']= paciente
    context['extrainfo'] = extra
    return context



class ItemInline(InlineFormSetFactory):
    model = farmacoterapia
    fields = ['farmaco', 'adminitracion', 'comentario']
    factory_kwargs = {'extra':7, 'max_num': None,
                      'can_order': False, 'can_delete': True}
    formset_kwargs = {'auto_id': 'my_id_%s','save_as_new': True}

class CreateOrderView(CreateWithInlinesView):
    model = Diagnostico
    inlines = [ItemInline]
    fields = ['paciente', 'precion_arterial', 'temperatura','peso','evolucion','pulso','saturacion_oxigeno','talla','idx','exmenes','motivo','encargado']
    template_name = 'registros/nuevo_diagnostico.html'
    inlines_names = ['Items', 'Tags']

    def get_success_url(self):
        parametro = self.kwargs.get('ident',None)
        return '/paciente/listar_diagnostico/{0}'.format(parametro)
    def get_initial(self, **kwargs):
        parametro = self.kwargs.get('ident',None)
        paciente = Paciente.objects.get(pk=parametro)
        return {'paciente':paciente,}
    def get_context_data(self, **kwargs):
        parametro = self.kwargs.get('ident',None)
        paciente = Paciente.objects.get(pk=parametro)
        context = super(CreateOrderView, self).get_context_data(**kwargs)
        extra={'title':'Diagnosticos','page':'Nuevo Diagnostico'}
        context['paciente']= paciente
        context['extrainfo'] = extra
        return context


#############################################
############# VISTA PRINCIPAL   #############
#############################################
class IndexView(generic.ListView):
	template_name='registros/index.html'
	context_object_name='all_albums'
	def get_queryset(self):
		return Paciente.objects.all()

################################################
############# BUSQUEDA DE PACIENTE #############
################################################
class BusquedaView(generic.ListView):
    template_name='registros/buscar.html' 
    model= Paciente

class BusquedaAjaxView(generic.TemplateView):
    def get(self,request,*args,**kwargs):
        var=request.GET['id']
        if var!='':
            new = Paciente.objects.filter(Q(nombre1__contains=var) | Q(apellPadre__contains=var) | Q(cedula__contains=var))
        else:
            new = {}
        data = serializers.serialize('json',new,fields=('cedula','nombre1','apellPadre','fech_actualizado'))
        return HttpResponse(data,content_type='application/json')

################################################
############# CREACION DE PACIENTE #############
################################################

class Crear_paciente(CreateView):
    model = Paciente
    fields='__all__'
    template_name='registros/paciente_form.html'
    success_url = '/buscar'
    success_message = 'Paciente creado correctamente'


class IngresoView(generic.ListView):
    template_name='registros/paciente.html'
    context_object_name='datos'
    def get_queryset(self, **kwargs):
        parametro = self.kwargs.get('ident',None)
        return Paciente.objects.get(pk=parametro)


class EcoView(generic.ListView):
    template_name='registros/ecografias.html'
    context_object_name='datos'
    def get_queryset(self, **kwargs):
        parametro = self.kwargs.get('ident',None)
        return Paciente.objects.get(pk=parametro)


##########################################################
##################FORMULARIOS PARA ECOGRAFIA##############
##########################################################

def get_initial_pri(self, **kwargs):
    parametro = self.kwargs.get('ident',None)
    paciente = Paciente.objects.get(pk=parametro)
    return {'paciente':paciente,}

def get_context_data_pri(self, nomclass,extra,**kwargs):
    parametro = self.kwargs.get('ident',None)
    paciente = Paciente.objects.get(pk=parametro)
    context = super(nomclass, self).get_context_data(**kwargs) 
    context['paciente']= paciente
    context['extrainfo'] = extra
    return context

class EcomamaCreate(CreateView):
    model = analisisMamas
    fields='__all__'
    template_name='registros/base_ecografias_form.html'
    context_object_name='datos'
    def get_success_url(self):
        parametro = self.kwargs.get('ident',None)
        return 'listar/{0}'.format(parametro)
    def get_initial(self, **kwargs):
        return get_initial_pri(self, **kwargs)
    def get_context_data(self, **kwargs):
        extrainfo={'title':'Ecografia Mamas','page':'Ecografia Mamas','verif':'true'}
        return get_context_data_pri(self,EcomamaCreate,extrainfo, **kwargs)

class EcoabdomenCreate(CreateView):
    model=analisisAbdominal
    fields='__all__'
    template_name='registros/base_ecografias_form.html'
    def get_success_url(self):
        parametro = self.kwargs.get('ident',None)
        return 'listar/{0}'.format(parametro)
    def get_initial(self, **kwargs):
        return get_initial_pri(self, **kwargs)
    def get_context_data(self, **kwargs):
        extrainfo={'title':'Ecografia abdominal','page':'Ecografia abdominal','verif':'true'}
        return get_context_data_pri(self,EcoabdomenCreate,extrainfo, **kwargs)

class EcoobstetricoCreate(CreateView):
    model=analisisObstetrico
    fields='__all__'
    template_name='registros/base_ecografias_form.html'
    def get_success_url(self):
        parametro = self.kwargs.get('ident',None)
        return 'listar/{0}'.format(parametro)
    def get_initial(self, **kwargs):
        return get_initial_pri(self, **kwargs)
    def get_context_data(self, **kwargs):
        extrainfo={'title':'Ecografia Obstetrico','page':'Ecografia Obstetrico','verif':'true'}
        return get_context_data_pri(self,EcoobstetricoCreate,extrainfo, **kwargs)

class EcorenalCreate(CreateView):
    model=ecografiaRenal
    fields='__all__'
    template_name='registros/base_ecografias_form.html'
    def get_success_url(self):
        parametro = self.kwargs.get('ident',None)
        return 'listar/{0}'.format(parametro)
    def get_initial(self, **kwargs):
        return get_initial_pri(self, **kwargs)
    def get_context_data(self, **kwargs):
        extrainfo={'title':'Ecografia Renal','page':'Ecografia Renal','verif':'true'}
        return get_context_data_pri(self,EcorenalCreate,extrainfo, **kwargs)

class EcoginecologiaCreate(CreateView):
    model=ecografiaginecologico
    fields='__all__'
    template_name='registros/base_ecografias_form.html'
    def get_success_url(self):
        parametro = self.kwargs.get('ident',None)
        return 'listar/{0}'.format(parametro)
    def get_initial(self, **kwargs):
        return get_initial_pri(self, **kwargs)
    def get_context_data(self, **kwargs):
        extrainfo={'title':'Ecografia Ginecologia','page':'Ecografia Ginecologia','verif':'true'}
        return get_context_data_pri(self,EcoginecologiaCreate,extrainfo, **kwargs)

class EcotesticularCreate(CreateView):
    model=ecografiatesticular
    fields='__all__'
    template_name='registros/base_ecografias_form.html'
    def get_success_url(self):
        parametro = self.kwargs.get('ident',None)
        return 'listar/{0}'.format(parametro)
    def get_initial(self, **kwargs):
        return get_initial_pri(self, **kwargs)
    def get_context_data(self, **kwargs):

Registros/templates/registros/listar_ecos/listar_ecoabdomen.html
{%extends "registros/base_listar.html"%}

{% block title %}Lista Ecografias de abdomen{% endblock %}

{% block tipoeco %}
<li class="breadcrumb-item"><a href="{% url 'registros:ecografia' ident=paciente.pk %}">Ecografias</a></li>
<li class="breadcrumb-item active" aria-current="page">Listar Ecografia abdomen</li>
{% endblock %}

{% block content %}
<table id="dtDynamicVerticalScrollExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th class="th-sm">Fecha Ecografia
          <i class="fa fa-sort float-right" aria-hidden="true"></i>
        </th>
        <th class="th-sm">Actualizar
            <i class="fa fa-sort float-right" aria-hidden="true"></i>
        </th>
        <th class="th-sm">Visualizar
                <i class="fa fa-sort float-right" aria-hidden="true"></i>
            </th>
      </tr>
      </tr>
    </thead>
  
    <tbody>
        {% for list in analisis %}
        <tr>
            <td>{{list.fech_analisisabdomen}}</td>
            <td><a class="btn btn-primary" href="#">Actualizar</a></td>
            <td><a class="btn btn-danger" href="#">PDF</a></td>
        </tr>
        {%endfor%}
    </tbody>

    <tfoot>
        <tr>
            <th>Fecha Ecografia</th>
            <th>Actualizar</th>
            <th>Visualizar</th>
        </tr>
    </tfoot>
  </table>
{% endblock %}

Registros/templates/registros/listar_ecos/listar_ecoginecologia.html
{%extends "registros/base_listar.html"%}

{% block title %}Lista Ecografias Ginecologia{% endblock %}

{% block tipoeco %}
<li class="breadcrumb-item"><a href="{% url 'registros:ecografia' ident=paciente.pk %}">Ecografias</a></li>
<li class="breadcrumb-item active" aria-current="page">Listar Ecografia Ginecologia</li>
{% endblock %}

{% block content %}
<table id="dtDynamicVerticalScrollExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th class="th-sm">Fecha Ecografia
          <i class="fa fa-sort float-right" aria-hidden="true"></i>
        </th>
        <th class="th-sm">Actualizar
            <i class="fa fa-sort float-right" aria-hidden="true"></i>
        </th>
        <th class="th-sm">Visualizar
                <i class="fa fa-sort float-right" aria-hidden="true"></i>
            </th>
      </tr>
      </tr>
    </thead>
  
    <tbody>
        {% for list in analisis %}
        <tr>
            <td>{{list.fech_informe}}</td>
            <td><a class="btn btn-primary" href="#">Actualizar</a></td>
            <td><a class="btn btn-danger" href="#">PDF</a></td>
        </tr>
        {%endfor%}
    </tbody>

    <tfoot>
        <tr>
            <th>Fecha Ecografia</th>
            <th>Actualizar</th>
            <th>Visualizar</th>
        </tr>
    </tfoot>
  </table>
{% endblock %}

Registros/templates/registros/listar_ecos/listar_ecomamas.html
{%extends "registros/base_listar.html"%}

{% block title %}Lista Ecografias Mamas{% endblock %}

{% block tipoeco %}
<li class="breadcrumb-item"><a href="{% url 'registros:ecografia' ident=paciente.pk %}">Ecografias</a></li>
<li class="breadcrumb-item active" aria-current="page">Listar Ecografia Mamas</li>
{% endblock %}

{% block content %}
<table id="dtDynamicVerticalScrollExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th class="th-sm">Fecha Ecografia
          <i class="fa fa-sort float-right" aria-hidden="true"></i>
        </th>
        <th class="th-sm">Actualizar
            <i class="fa fa-sort float-right" aria-hidden="true"></i>
        </th>
        <th class="th-sm">Visualizar
                <i class="fa fa-sort float-right" aria-hidden="true"></i>
            </th>
      </tr>
      </tr>
    </thead>
  
    <tbody>
        {% for list in analisis %}
        <tr>
            <td>{{list.fech_analisismamas}}</td>
            <td><a class="btn btn-primary" href="#">Actualizar</a></td>
            <td><a class="btn btn-danger" href="#">PDF</a></td>
        </tr>
        {%endfor%}
    </tbody>

    <tfoot>
        <tr>
            <th>Fecha Ecografia</th>
            <th>Actualizar</th>
            <th>Visualizar</th>
        </tr>
    </tfoot>
  </table>
{% endblock %}

Registros/templates/registros/listar_ecos/listar_ecoobstetrico.html
{%extends "registros/base_listar.html"%}

{% block title %}Lista Ecografias Obstetrico{% endblock %}

{% block tipoeco %}
<li class="breadcrumb-item"><a href="{% url 'registros:ecografia' ident=paciente.pk %}">Ecografias</a></li>
<li class="breadcrumb-item active" aria-current="page">Listar Ecografia Obstetrico</li>
{% endblock %}

{% block content %}
<table id="dtDynamicVerticalScrollExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th class="th-sm">Fecha Ecografia
          <i class="fa fa-sort float-right" aria-hidden="true"></i>
        </th>
        <th class="th-sm">Actualizar
            <i class="fa fa-sort float-right" aria-hidden="true"></i>
        </th>
        <th class="th-sm">Visualizar
                <i class="fa fa-sort float-right" aria-hidden="true"></i>
            </th>
      </tr>
      </tr>
    </thead>
  
    <tbody>
        {% for list in analisis %}
        <tr>
            <td>{{list.fech_analisisobstetrico}}</td>
            <td><a class="btn btn-primary" href="#">Actualizar</a></td>
            <td><a class="btn btn-danger" href="#">PDF</a></td>
        </tr>
        {%endfor%}
    </tbody>

    <tfoot>
        <tr>
            <th>Fecha Ecografia</th>
            <th>Actualizar</th>
            <th>Visualizar</th>
        </tr>
    </tfoot>
  </table>
{% endblock %}

Registros/templates/registros/listar_ecos/listar_ecorenal.html
{%extends "registros/base_listar.html"%}

{% block title %}Lista Ecografias Renal{% endblock %}

{% block tipoeco %}
<li class="breadcrumb-item"><a href="{% url 'registros:ecografia' ident=paciente.pk %}">Ecografias</a></li>
<li class="breadcrumb-item active" aria-current="page">Listar Ecografia Renal</li>
{% endblock %}

{% block content %}
<table id="dtDynamicVerticalScrollExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th class="th-sm">Fecha Ecografia
          <i class="fa fa-sort float-right" aria-hidden="true"></i>
        </th>
        <th class="th-sm">Actualizar
            <i class="fa fa-sort float-right" aria-hidden="true"></i>
        </th>
        <th class="th-sm">Visualizar
                <i class="fa fa-sort float-right" aria-hidden="true"></i>
            </th>
      </tr>
      </tr>
    </thead>
  
    <tbody>
        {% for list in analisis %}
        <tr>
            <td>{{list.fech_informe}}</td>
            <td><a class="btn btn-primary" href="#">Actualizar</a></td>
            <td><a class="btn btn-danger" target="_blank" href="{% url 'registros:info_ecomamas' ident=list.pk %}">PDF</a></td>
        </tr>
        {%endfor%}
    </tbody>

    <tfoot>
        <tr>
            <th>Fecha Ecografia</th>
            <th>Actualizar</th>
            <th>Visualizar</th>
        </tr>
    </tfoot>
  </table>
{% endblock %}

Registros/templates/registros/listar_ecos/listar_ecotesticular.html
{%extends "registros/base_listar.html"%}

{% block title %}Lista Ecografias Testicular{% endblock %}

{% block tipoeco %}
<li class="breadcrumb-item"><a href="{% url 'registros:ecografia' ident=paciente.pk %}">Ecografias</a></li>
<li class="breadcrumb-item active" aria-current="page">Listar Ecografia Testicular</li>
{% endblock %}

{% block content %}
<table id="dtDynamicVerticalScrollExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th class="th-sm">Fecha Ecografia
          <i class="fa fa-sort float-right" aria-hidden="true"></i>
        </th>
        <th class="th-sm">Actualizar
            <i class="fa fa-sort float-right" aria-hidden="true"></i>
        </th>
        <th class="th-sm">Visualizar
                <i class="fa fa-sort float-right" aria-hidden="true"></i>
            </th>
      </tr>
      </tr>
    </thead>
  
    <tbody>
        {% for list in analisis %}
        <tr>
            <td>{{list.fech_informe}}</td>
            <td><a class="btn btn-primary" href="#">Actualizar</a></td>
            <td><a class="btn btn-danger" href="#">PDF</a></td>
        </tr>
        {%endfor%}
    </tbody>

    <tfoot>
        <tr>
            <th>Fecha Ecografia</th>
            <th>Actualizar</th>
            <th>Visualizar</th>
        </tr>
    </tfoot>
  </table>
{% endblock %}